#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from words import text_to_list
from db import Db
import os,sys,string,re,csv
import nltk,sqlite3
reload(sys)
sys.setdefaultencoding('utf8')

class classify():
	min_freq = 5 # change the stats after taking avg of min vs max repeats
	less_freq_prob = 0.5
	max_freq_prob = 0.99

	def set_text(self,text): #just pass list here one line only
		self.text = text
		lines = [] # shorten this later
		words = text_to_list(line)
		if not len(words):
			raise ValueError ('Text doesnt contain valid keywords') ## sabb ma nepali message pass garnu
		else:
			for word in words:
				lines.append(word)

		self.lines = lines
		return self

	def find_values(self,word):
		db = Db()
		total_p = db.get_words_count('p')
		total_n = db.get_words_count('n')
		word_p = db.get_word_count('p',word)
		word_n = db.get_word_count('n',word)

		if word_p + word_n < min_freq:
			return less_freq_prob
		if word_p == 0:
			return 1- max_freq_prob
		elif word_n=0:
			return max_freq_prob

		p_wp = float(word_p/total_p)
		p_wn = float(word_n/total_n)

		return p_wp/(p_wp+p_wn)

	def find_values_list(self,l):
		##find values of each word in the list :D##
		p_product         = reduce(lambda x,y: x*y, l) #copied need to understand this
		p_inverse_product = reduce(lambda x,y: x*y, map(lambda x: 1-x, l))

		return p_product / (p_product + p_inverse_product)

	def execute(lines):
		polcount = 0
		prob_list = []
		db = Db()
		db.get_polwords()
		lines = lines.replace("|")
		for each in lines.split():
			if each.strip() not in polwords:
				problist.append(find_values(each.strip()))
			else:
				polcount += 1
		result = (find_values_list(problist))
		if polcount%2:
			result = 1-result